/*
 * This file is generated by jOOQ.
 */
package com.example.poc.jooq;


import com.example.poc.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class College extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>college</code>
     */
    public static final College COLLEGE = new College();

    /**
     * The table <code>college.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private College() {
        super("college", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Users.USERS
        );
    }
}
