/*
 * This file is generated by jOOQ.
 */
package com.example.poc.jooq;


import com.example.poc.jooq.tables.Users;


/**
 * Convenience access to all tables in college.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>college.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
